parameters:
  repositoryName: ""
  branchName: ""
  resourceName: ""
  runCheckoutCode: true
  cleanCheckout: true
  listFiles: true

#-- Steps --#
steps:
  #-- Display Environment Variables --#
  - task: PowerShell@2
    displayName: Display Environment Variables
    inputs:
      targetType: inline
      script: |
        Get-ChildItem Env: | ForEach-Object { Write-Host "`nName : $($_.Name)`nValue: $($_.Value)" }
    condition: and(succeeded(), ${{ parameters.runCheckoutCode }})

  #-- Checkout the Code Repository --#
  - checkout: ${{ parameters.resourceName }}
    displayName: Checkout Repository ${{ parameters.repositoryName }} - Branch ${{ parameters.branchName }} - Resource ${{ parameters.resourceName }}
    persistCredentials: true
    clean: ${{ parameters.cleanCheckout }}
    condition: and(succeeded(), ${{ parameters.runCheckoutCode }})

  #-- Listing Checkout files --#
  - task: PowerShell@2
    displayName: Listing checkout files
    inputs:
      targetType: inline
      script: |
        Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse -Force
    condition: and(succeeded(), ${{ parameters.runCheckoutCode }}, ${{ parameters.listFiles }})
